### ISSUE TITLE
AH-64D Altimeter  version 1.6.6101.1

### ISSUE THREAD

**Issue by Guggenheimeren** [HeliosVirtualCockpit/HeliosInterfaces#18]
Does not work in DCS AH64 and AH64 PLT
MPD buttons does not funciton in DCS AH64 and screen not focused properly

**Comment by BlueFinBima** [comment]
Helios 1.6.6100.4 was missing a vital file for the Apache.  If you saved your profile while using this release, the bindings (which link DCS to the profile controls) will have been deleted.  You can quickly check this by examining the `xxx.hpf` file against a backup of the profile.  If the bindings are missing, then the profile file size will be smaller.  You will need to restore a version of your profile which was not saved under 1.6.6100.4.

Please refer to [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios) for how to receive community support for Helios issues.  

Regards

**Comment by Guggenheimeren** [comment]
Thank’s a lot for your kindly answer. Everything back to normal now!
Except the altimeter in each profile, which never worked. Aceflight, whom
you helped doing the utility, must be aware of the problem as several
mentioned it in his Apache Helios Profile.


Kindly regards
Jan T.
Denmark


søn. 8. sep. 2024 kl. 11.17 skrev BlueFinBima ***@***.***>:

**Comment by BlueFinBima** [comment]
Hi Jan,  I'm glad that you're back in action.  I've just tested the Apache altimeter and it works fine for me.  
I closed this issue because I would like you to use the community support on Capt Zeen's Discord as I previously outlined in [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios).  I feel sure that you'll be able to find an answer to your altimeter problem there. 
Regards.
